pipeline {
  agent none

  stages {
    stage('Backend') {
      agent {
        docker {
          image 'maven:3.9.0-eclipse-temurin-17'
          label 'docker'
          args '-v $HOME/.m2:/root/.m2'  # Cache Maven dependencies
        }
      }
      steps {
        checkout scm
        sh 'mvn clean compile'
        sh 'mvn test'
        sh 'mvn package'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
