pipeline {
  agent none
  stages {
    agent {
      docker {
        image 'maven:3.9.0-eclipse-temurin-17'
        label 'docker'
        args '-v $HOME/.m2:/root/.m2'  // Reuse Maven cache
      }
    }
    stage('Checkout') {
      steps {
          checkout scm
      }
    }

    stage('Build') {
      steps {
          sh 'mvn clean compile'
      }
    }

    stage('Test') {
      steps {
          sh 'mvn test'
      }
    }

    stage('Package') {
      steps {
          sh 'mvn package'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
