pipeline {
  agent none

  stages {
    stage('Backend') {
      agent {
        docker {
          image 'maven:3.9.0-eclipse-temurin-17'
          args '-v $HOME/.m2:/root/.m2'  // Cache Maven dependencies
        }
      }
      steps {
        checkout scm
        sh 'mvn -f multi-stage-multi-agent/pom.xml clean compile'
        sh 'mvn -f multi-stage-multi-agent/pom.xml test'
        sh 'mvn -f multi-stage-multi-agent/pom.xml package'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
